import { AppThemeProvider } from "@/shared/ui/theme/AppThemeProvider";
import { CssBaseline } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AppThemeProvider>
            <CssBaseline>
              {children}
            </CssBaseline>
          </AppThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
